# Generated by Django 6.0.6 on 2026-06-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
